name: Instana GitOps update

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: instana/github-action-update-agent-configurations@v1.0.0
        with:
          agent_tags: 'gitops_environment=prod'
        env:
          INSTANA_API_ENDPOINT: ${{ secrets.INSTANA_API_ENDPOINT }}
          INSTANA_API_TOKEN: ${{ secrets.INSTANA_API_TOKEN }}
